Entity/Motw.php
<?php

namespace ATM\MotwBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use \DateTime;

/**
 * @ORM\Entity(repositoryClass="ATM\MotwBundle\Repository\MotwRepository")
 * @ORM\Table(name="atm_motw")
 */
class Motw{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    protected $model;

    /**
     * @ORM\Column(name="creation_date", type="datetime", nullable=false)
     */
    private $creation_date;

    /**
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(name="init_date", type="datetime")
     */
    private $init_date;

    /**
     * @ORM\Column(name="end_date", type="datetime")
     */
    private $end_date;

    /**
     * @ORM\Column(name="thumbnail_members", type="text", nullable=false)
     */
    private $thumbnail_members;

    /**
     * @ORM\Column(name="thumbnail_members_mobile", type="text", nullable=false)
     */
    private $thumbnail_members_mobile;

    /**
     * @ORM\Column(name="thumbnail_tour", type="text", nullable=false)
     */
    private $thumbnail_tour;

    /**
     * @ORM\Column(name="thumbnail_tour_mobile", type="text", nullable=false)
     */
    private $thumbnail_tour_mobile;

    /**
     * @ORM\Column(name="folderName", type="string", length=255, nullable=false)
     */
    private $folderName;

    public function __construct()
    {
        $this->creation_date = new DateTime();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getModel()
    {
        return $this->model;
    }

    public function setModel($model)
    {
        $this->model = $model;
    }

    public function getCreationDate()
    {
        return $this->creation_date;
    }

    public function setCreationDate($creation_date)
    {
        $this->creation_date = $creation_date;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($description)
    {
        $this->description = $description;
    }

    public function getInitDate()
    {
        return $this->init_date;
    }

    public function setInitDate($init_date)
    {
        $this->init_date = $init_date;
    }

    public function getEndDate()
    {
        return $this->end_date;
    }

    public function setEndDate($end_date)
    {
        $this->end_date = $end_date;
    }

    public function getThumbnailMembers()
    {
        return $this->thumbnail_members;
    }

    public function setThumbnailMembers($thumbnail_members)
    {
        $this->thumbnail_members = $thumbnail_members;
    }

    public function getThumbnailTour()
    {
        return $this->thumbnail_tour;
    }

    public function setThumbnailTour($thumbnail_tour)
    {
        $this->thumbnail_tour = $thumbnail_tour;
    }

    public function getFolderName()
    {
        return $this->folderName;
    }

    public function setFolderName($folderName)
    {
        $this->folderName = $folderName;
    }

    public function getThumbnailMembersMobile()
    {
        return $this->thumbnail_members_mobile;
    }

    public function setThumbnailMembersMobile($thumbnail_members_mobile)
    {
        $this->thumbnail_members_mobile = $thumbnail_members_mobile;
    }

    public function getThumbnailTourMobile()
    {
        return $this->thumbnail_tour_mobile;
    }

    public function setThumbnailTourMobile($thumbnail_tour_mobile)
    {
        $this->thumbnail_tour_mobile = $thumbnail_tour_mobile;
    }
}

Resources/views/Admin/base.html.twig
<html>
<head>
    <meta charset="UTF-8" />
    <title>{% block atm_motw_title %}ATM Model of the week Bundle{% endblock atm_motw_title %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="Distribution" content="Global" />
    <meta name="Rating" content="Mature" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('bundles/atmmotw/css/css.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/atmmotw/css/font-awesome/css/font-awesome.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/atmmotw/fonts/lato.css') }}" type="text/css"/>
    <link rel="stylesheet" href="{{ asset('bundles/atmmotw/fonts/quicksand.css') }}" type="text/css"/>
    <link rel="stylesheet" href="{{ asset('bundles/atmmotw/fonts/leaguespartan.css') }}" type="text/css"/>
    <script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
    <script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>
    {% block atm_motw_stylesheets %}{% endblock atm_motw_stylesheets %}
    {% block atm_motw_jquery %}
        <script src="{{ asset('bundles/atmmotw/js/jquery-1.11.2.js') }}"></script>
    {% endblock atm_motw_jquery %}
    {% block atm_motw_headingJS %}{% endblock atm_motw_headingJS %}
</head>
<body class="atm_motw">
<div class="inner body">
    {% block atm_motw_content %}{% endblock atm_motw_content %}
</div>
{% block atm_motw_javascripts %}
{% endblock atm_motw_javascripts %}
</body>
</html>

Resources/views/Admin/create.html.twig
{% extends 'ATMMotwBundle:Admin:base.html.twig' %}

{% block atm_motw_stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/atmmotw/css/jquery-ui.css') }}">
    <style>
        #uploaded_images li{float: left;margin:10px 35px 0 0;;width: auto;}
        #uploaded_images li img{width: 200px;min-height: 200px;}
        #motw_init_date, #motw_end_date{width:50%}
    </style>
{% endblock atm_motw_stylesheets %}


{% block atm_motw_content %}
    <div class="mm_media_bundle_wrapper mm_video_create">
        <form action="{{ path('atm_motw_create') }}" method="post" enctype="multipart/form-data" class="cont" style="border: none;">
            <fieldset style="position: relative;width: auto;">
                <div class="selectC">
                    {{ form_widget(form.model) }}
                </div>
            </fieldset>
            <div class="clear"></div>

            <fieldset>
                {{ form_widget(form.init_date) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.end_date) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.description) }}
            </fieldset>
            <fieldset style="float: left;width: 50%;">
                <legend style="text-align: center;">Thumbnail Tour</legend>
                <img src="{{ asset('bundles/atmmotw/images/image-placeholder.png') }}" style="width: 250px;display: block;float: none;">
                <input type="file" name="motwThumbnailTour" class="motwThumbnail" required style="margin: 10px 0 30px;;">
            </fieldset>
            <fieldset style="float: left;width: 50%;">
                <legend style="text-align: center;">Thumbnail Tour Mobile (420 x 280)</legend>
                <img src="{{ asset('bundles/atmmotw/images/image-placeholder.png') }}" style="width: 250px;display: block;float: none;">
                <input type="file" name="motwThumbnailTourMobile" class="motwThumbnail" required style="margin: 10px 0 30px;;">
            </fieldset>
            <fieldset style="float: left;width: 50%;">
                <legend style="text-align: center;">Thumbnail Members</legend>
                <img src="{{ asset('bundles/atmmotw/images/image-placeholder.png') }}" style="width: 250px;display: block;float: none;">
                <input type="file" name="motwThumbnailMembers" class="motwThumbnail" required  style="margin: 10px 0 30px;;">
            </fieldset>
            <fieldset style="float: left;width: 50%;">
                <legend style="text-align: center;">Thumbnail Members (420 x 280)</legend>
                <img src="{{ asset('bundles/atmmotw/images/image-placeholder.png') }}" style="width: 250px;display: block;float: none;">
                <input type="file" name="motwThumbnailMembersMobile" class="motwThumbnail" required style="margin: 10px 0 30px;;">
            </fieldset>
            {{ form_rest(form) }}
            <div class="clear"></div>
            <input type="hidden" name="folderName" value="{{ folderName }}">
            <input type="submit" id="sbCreateMotw" value="Save" style="display:none;">
        </form>
        <a class="but blue" onclick="$('#sbCreateMotw').click();">Save</a>
    </div>
{% endblock atm_motw_content %}

{% block atm_motw_javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/atmmotw/js/jquery-ui.min.1121.js') }}"></script>
    <script>
        $( function() {
            var dateFormat = "dd-mm-yy",
                from = $( "#motw_init_date" )
                    .datepicker({
                        dateFormat: dateFormat,
                        changeMonth: true,
                        numberOfMonths: 3
                    }).on( "change", function() {
                        to.datepicker( "option", "minDate", getDate( this ) );
                    }),
                to = $( "#motw_end_date" ).datepicker({
                    dateFormat: dateFormat,
                    defaultDate: "+1w",
                    changeMonth: true,
                    numberOfMonths: 3
                }).on( "change", function() {
                    from.datepicker( "option", "maxDate", getDate( this ) );
                });

            function getDate( element ) {
                var date;
                try {
                    date = $.datepicker.parseDate( dateFormat, element.value );
                } catch( error ) {
                    date = null;
                }

                return date;
            }
        } );

        $('.motwThumbnail').change(function(){
            var currentInput = $(this);
            var file = currentInput[0].files[0];

            var reader = new FileReader();
            reader.onload = function(e){
                currentInput.siblings('img').attr('src', e.target.result);
            };
            reader.readAsDataURL(file);
        });
    </script>
{% endblock atm_motw_javascripts %}

Resources/views/Admin/edit.html.twig
{% extends 'ATMMotwBundle:Admin:base.html.twig' %}

{% block atm_motw_stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/atmmotw/css/jquery-ui.css') }}">
    <style>
        #uploaded_images li{float: left;margin:10px 35px 0 0;;width: auto;}
        #uploaded_images li img{width: 200px;min-height: 200px;}
        #motw_init_date, #motw_end_date{width:50%}
    </style>
{% endblock atm_motw_stylesheets %}


{% block atm_motw_content %}
    <div class="mm_media_bundle_wrapper mm_video_create">
        <form action="{{ path('atm_motw_edit',{ 'motwId':motw.id }) }}" method="post" enctype="multipart/form-data" class="cont" style="border: none;">
            <fieldset style="position: relative;width: auto;">
                <div class="selectC">
                    {{ form_widget(form.model) }}
                </div>
            </fieldset>
            <div class="clear"></div>

            <fieldset>
                {{ form_widget(form.init_date) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.end_date) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.description) }}
            </fieldset>
            <fieldset style="float: left;width: 50%;">
                <legend style="text-align: center;">Thumbnail Tour</legend>
                <img src="{{ asset(motw.thumbnailTour) }}" style="width: 250px;display: block;float: none;">
                <input type="file" name="motwThumbnailTour" class="motwThumbnail" style="margin: 10px 0 30px;;">
            </fieldset>
            <fieldset style="float: left;width: 50%;">
                <legend style="text-align: center;">Thumbnail Tour Mobile (420 x 280)</legend>
                <img src="{{ motw.thumbnailTourMobile ? asset(motw.thumbnailTourMobile) : asset('bundles/atmmotw/images/image-placeholder.png') }}" style="width: 250px;display: block;float: none;">
                <input type="file" name="motwThumbnailTourMobile" class="motwThumbnail" style="margin: 10px 0 30px;;">
            </fieldset>
            <fieldset style="float: left;width: 50%;">
                <legend style="text-align: center;">Thumbnail Members</legend>
                <img src="{{ asset(motw.thumbnailMembers) }}" style="width: 250px;display: block;float: none;">
                <input type="file" name="motwThumbnailMembers" class="motwThumbnail" style="margin: 10px 0 30px;;">
            </fieldset>
            <fieldset style="float: left;width: 50%;">
                <legend style="text-align: center;">Thumbnail Members Mobile (420 x 280)</legend>
                <img src="{{ motw.thumbnailMembersMobile ? asset(motw.thumbnailMembersMobile) : asset('bundles/atmmotw/images/image-placeholder.png') }}" style="width: 250px;display: block;float: none;">
                <input type="file" name="motwThumbnailMembersMobile" class="motwThumbnail" style="margin: 10px 0 30px;;">
            </fieldset>
            {{ form_rest(form) }}
            <div class="clear"></div>
            <input type="submit" id="sbCreateMotw" value="Save" style="display:none;">
        </form>
        <a class="but blue" onclick="$('#sbCreateMotw').click();">Save</a>
    </div>
{% endblock atm_motw_content %}

{% block atm_motw_javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/atmmotw/js/jquery-ui.min.1121.js') }}"></script>
    <script>
        $( function() {
            var dateFormat = "dd-mm-yy",
                from = $( "#motw_init_date" )
                    .datepicker({
                        dateFormat: dateFormat,
                        defaultDate: {{ motw.initDate | date('d-m-Y') }},
                        changeMonth: true,
                        numberOfMonths: 3
                    }).on( "change", function() {
                        to.datepicker( "option", "minDate", getDate( this ) );
                    }),
                to = $( "#motw_end_date" ).datepicker({
                    dateFormat: dateFormat,
                    defaultDate: {{ motw.endDate | date('d-m-Y') }},
                    changeMonth: true,
                    numberOfMonths: 3
                }).on( "change", function() {
                    from.datepicker( "option", "maxDate", getDate( this ) );
                });

            function getDate( element ) {
                var date;
                try {
                    date = $.datepicker.parseDate( dateFormat, element.value );
                } catch( error ) {
                    date = null;
                }

                return date;
            }
        } );

        $('.motwThumbnail').change(function(){
            var currentInput = $(this);
            var file = currentInput[0].files[0];

            var reader = new FileReader();
            reader.onload = function(e){
                currentInput.siblings('img').attr('src', e.target.result);
            };
            reader.readAsDataURL(file);
        });
    </script>
{% endblock atm_motw_javascripts %}

Resources/views/Admin/index.html.twig
{% extends 'ATMMotwBundle:Admin:base.html.twig' %}

{% block atm_motw_stylesheets %}
    <style>
        .menu{width: 100%;margin-bottom: 40px !important;text-align: left;}
        .menu ul, .menu li,.menu a{float:none}
        .motw{width: 25%;float: left;margin-left: 15px;position:relative}
        .motw .controls{float: none;position: absolute;z-index: 1;padding: 5px;background-color: #00000061;width: 100%;}
        .motw .controls .edit{float: left;color: #fff;}
        .motw .controls .delete{float: right;color: #fff;}
        .motw:hover .members{display:block}
        .motw:hover .tour span{display:none}
        .motw .data{}
        .motw .data span{}
        .motw .data h3{width: 100%;text-align: center;font-weight: bold;margin-bottom: 5px;}
        .motw .tour{position: relative;}
        .motw .tour span{position: absolute;bottom: 0;z-index: 1;width: 100%;left: 0;background-color: #00000054;color: #fff;}
        .motw .tour img{float: none;width: 100%;}
        .motw .members{display:none;position: absolute;top: 0;right: 0;}
        .motw .members span{position: absolute;bottom: 0;z-index: 1;width: 100%;left: 0;background-color: #00000054;color: #fff;}
        .motw .members img{float: none;width: 100%;}
    </style>
{% endblock atm_motw_stylesheets %}


{% block atm_motw_content %}
    <div class="menu">
        <ul>
            <li>
                <a href="{{ path('atm_motw_create') }}" style="font-weight: bold;">Create new model of the week</a>
            </li>
        </ul>
    </div>
    <div class="mm_media_bundle_wrapper mm_video_create">
        {% for motw in motws %}
            {% include 'ATMMotwBundle:Admin:item/motw.html.twig' with { 'motw':motw } %}
        {% endfor %}

        {% if pagination %}
            <div class="navigation">
                {{ knp_pagination_render(pagination) }}
            </div>
        {% endif %}
        <div class="clear"></div>
    </div>
{% endblock atm_motw_content %}